---
- name: Setup env specific variables
  set_fact:
#    tp_path: "{{ playbook_dir }}/../cloud_aws/provision/templates/{{ cluster.target_os }}.j2"
    ip_pos: "{{ inventory_hostname | replace(cluster.name_prefix, '') }}"
    aws_usr_key: "{{ auth.username }}"
    aws_sec_key: "{{ auth.password }}"
    region: "{{ cluster.region_name | default('us-east-1') }}"


#- name: ensure backup directories are present
#  debug: "{{inventory_hostname}}"
#  with_items: "{{ ansible_play_hosts }}"

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: ../../workspace/{{proj}}/run/outputhosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}" 
