---
- name: Init Cloud environment global variables
  hosts: cloud
  connection: local
  vars_files:
    - "./../../vars/{{ cloud }}.yml"
#  tasks:
#    - include: "prepare/tasks/{{ mode }}.yml"
  tags: "Init-Cloud"

- name: Authenticate to the cloud
  hosts: localhost
  connection: local
  strategy: free
  vars_files:
    - "./../../vars/{{ cloud }}.yml"
    - "./../../workspace/{{ proj }}/credvars.yml"
  tasks:
    - include: "creds/tasks/{{ mode }}.yml"
  tags: "creds"

- name: Cloud Topology definition
  hosts: localhost
  connection: local
  strategy: free
  vars_files:
    - "./../../workspace/{{ proj }}/topologyvars.yml"
    - "./../../vars/{{ cloud }}.yml"
  tasks:
    - include: "topology/tasks/{{ mode }}.yml"
  tags: "topology"

- name: Prepare the environment
  hosts: localhost
  connection: local
  vars_files:
    - "./../../workspace/{{ proj }}/preparevars.yml"
    - "./../../vars/{{ cloud }}.yml"
  tasks:
    - include: "prepare/tasks/{{ mode }}.yml"
  tags: "prepare"

- name: Provision the server
  hosts: prohosts
  connection: local
  vars_files:
    - "./../../workspace/{{ proj }}/provisionvars.yml"
    - "./../../vars/{{ cloud }}.yml"
  tasks:
    - include: "provision/tasks/{{ mode }}.yml"
  tags: "prepare"

- name: Post Provision server prereqs
  hosts: cloud
  connection: local
  vars_files:
    - "./../../workspace/{{ proj }}/postprovvars.yml"
    - "./../../vars/{{ cloud }}.yml"
  tasks:
    - include: "provision/tasks/{{ mode }}.yml"
  tags: "prepare"

- name: Deployment of software assets
  hosts: cloud
  connection: local
  vars_files:
    - "./../../workspace/{{ proj }}/deployvars.yml"
    - "./../../vars/{{ cloud }}.yml"
  tasks:
    - include: "provision/tasks/{{ mode }}.yml"
  tags: "prepare"


