---
- name: Setup env specific variables
  set_fact:
#    tp_path: "{{ playbook_dir }}/../cloud_aws/provision/templates/{{ cluster.target_os }}.j2"
    ip_pos: "{{ inventory_hostname | replace(cluster.name_prefix, '') }}"
    aws_usr_key: "{{ auth.username }}"
    aws_sec_key: "{{ auth.password }}"
    region: "{{ cluster.region_name | default('us-east-1') }}"
    
